/**
 * Root convenience barrel for the ADK's core runtime values and public TypeScript contracts.
 *
 * @module @nhtio/adk
 */

/**
 * The current version of the package.
 *
 * @tip This is a constant that is replaced during the build process with the actual version of the package.
 */
export const version = __VERSION__

// ── Data primitives (value classes + Raw* types) ──────────────────────────────

export type {
  TokenizableEvaluator,
  TokenEncodingId,
  TokenEstimatorFn,
} from './lib/classes/tokenizable'
export { registerTokenEstimator } from './lib/classes/tokenizable'
export {
  Tokenizable,
  TokenEncoding,
  Registry,
  Identity,
  Memory,
  Message,
  Retrievable,
  Thought,
  ToolCall,
  Tool,
  ArtifactTool,
  ToolRegistry,
  SpooledArtifact,
  SpooledJsonArtifact,
  SpooledMarkdownArtifact,
  implementsSpoolReader,
  Media,
  isMedia,
  implementsMediaReader,
  mediaReaderSchema,
  inMemoryMediaReader,
  fromFetch,
  fromWebFile,
} from './common'

export type {
  RawMedia,
  SerializedMedia,
  MediaKind,
  MediaTrustTier,
  MediaModalityHazard,
  MediaStashEntry,
  MediaReader,
} from './common'

// ── Runners (the entry points for executing turns and dispatches) ─────────────

export { TurnRunner } from './turn_runner'
export { DispatchRunner } from './dispatch_runner'

// ── Freestanding guards ───────────────────────────────────────────────────────

export {
  isInstanceOf,
  isError,
  isObject,
  isBaseException,
  isIdentity,
  isMemory,
  isMessage,
  isRegistry,
  isThought,
  isTokenizable,
  isTool,
  isArtifactTool,
  isToolCall,
  isToolRegistry,
  isTurnGate,
  isSpooledArtifact,
  isSpooledArtifactConstructor,
  isSpooledJsonArtifact,
  isSpooledMarkdownArtifact,
  isTurnContext,
  isTurnRunner,
  isDispatchContext,
  isDispatchRunner,
} from './guards'

// ── Exceptions ────────────────────────────────────────────────────────────────

export {
  ValidationException,
  E_INVALID_TURN_RUNNER_CONFIG,
  E_INVALID_TURN_CONTEXT,
  E_INPUT_PIPELINE_ERROR,
  E_OUTPUT_PIPELINE_ERROR,
  E_PIPELINE_SHORT_CIRCUITED,
  E_INVALID_INITIAL_REGISTRY_VALUE,
  E_INVALID_INITIAL_MEMORY_VALUE,
  E_INVALID_INITIAL_MESSAGE_VALUE,
  E_INVALID_INITIAL_IDENTITY_VALUE,
  E_INVALID_INITIAL_THOUGHT_VALUE,
  E_INVALID_INITIAL_TURN_GATE_VALUE,
  E_INVALID_TURN_GATE_RESOLUTION,
  E_TURN_GATE_TIMEOUT,
  E_TURN_GATE_ABORTED,
  E_NOT_A_SPOOL_READER,
  E_INVALID_INITIAL_TOOL_CALL_VALUE,
  E_INVALID_INITIAL_TOOL_VALUE,
  E_INVALID_TOOL_ARGS,
  E_TOOL_DOWNSTREAM_ERROR,
  E_TOOL_ALREADY_REGISTERED,
  E_INVALID_LLM_EXECUTION_CONTEXT,
  E_LLM_EXECUTION_GATE_NOT_SUPPORTED,
  E_LLM_EXECUTION_ALREADY_SIGNALLED,
  E_INVALID_LLM_DISPATCH_INPUT,
  E_DISPATCH_PIPELINE_ERROR,
  E_LLM_EXECUTION_EXECUTOR_ERROR,
  E_READER_NOT_DESCRIBABLE,
  E_NO_READER_RESOLVER,
  E_ARTIFACT_ID_COLLISION,
  E_TOKENIZABLE_EVALUATOR_INVALID,
} from './exceptions'
export { E_TOKEN_ESTIMATOR_SHADOWS_BUILTIN } from './lib/classes/tokenizable'

// ── Types (re-exported via `export type *` form) ──────────────────────────────

export type {
  BaseException,
  TurnContext,
  DispatchContext,
  TurnGate,
  RawIdentity,
  RawMemory,
  RawMessage,
  MessageRole,
  RawThought,
  RawToolCall,
  RawTool,
  ToolHandler,
  RawArtifactTool,
  ArtifactToolHandler,
  MergeOptions,
  SpooledArtifactConstructor,
  ToolMethodDescriptor,
  RawTurnGate,
  SpoolReader,
  JsonArtifactFormat,
  MarkdownHeadingEntry,
  MarkdownCodeEntry,
  MarkdownSection,
  RawTurnContext,
  ResolvedTurnContext,
  MemoryRetrievalFn,
  MessageRetrievalFn,
  ThoughtRetrievalFn,
  ToolCallRetrievalFn,
  ToolsRetrievalFn,
  RetrievableRetrievalFn,
  StandingInstructionsRefreshFn,
  StandingInstructionStoreFn,
  StandingInstructionMutateFn,
  StandingInstructionDeleteFn,
  MemoryStoreFn,
  MemoryMutateFn,
  MemoryDeleteFn,
  MessageStoreFn,
  MessageMutateFn,
  MessageDeleteFn,
  ThoughtStoreFn,
  ThoughtMutateFn,
  ThoughtDeleteFn,
  ToolCallStoreFn,
  ToolCallMutateFn,
  ToolCallDeleteFn,
  RetrievableStoreFn,
  RetrievableMutateFn,
  RetrievableDeleteFn,
  MediaBytesStoreFn,
  RetrievableBytesStoreFn,
  TurnRunnerConfig,
  ResolvedTurnRunnerConfig,
  TurnPipelineMiddlewareFn,
  TurnStreamableContent,
  TurnToolCallContent,
  TurnStartEvent,
  TurnEndEvent,
  TurnGateClosedEvent,
  ToolExecutionStartEvent,
  ToolExecutionEndEvent,
  EmitMessageFn,
  EmitThoughtFn,
  EmitToolCallFn,
  EmitToolExecutionStartFn,
  EmitToolExecutionEndFn,
  OpenGateFn,
  TurnEvents,
  TurnEvent,
  TurnEventListener,
  TurnObservabilityEvents,
  TurnObservabilityEvent,
  TurnObservabilityEventListener,
  RawDispatchContext,
  DispatchMemoryRetrievalFn,
  DispatchMessageRetrievalFn,
  DispatchThoughtRetrievalFn,
  DispatchToolCallRetrievalFn,
  DispatchToolsRetrievalFn,
  DispatchStandingInstructionsRefreshFn,
  DispatchStandingInstructionStoreFn,
  DispatchStandingInstructionMutateFn,
  DispatchStandingInstructionDeleteFn,
  DispatchMemoryStoreFn,
  DispatchMemoryMutateFn,
  DispatchMemoryDeleteFn,
  DispatchMessageStoreFn,
  DispatchMessageMutateFn,
  DispatchMessageDeleteFn,
  DispatchThoughtStoreFn,
  DispatchThoughtMutateFn,
  DispatchThoughtDeleteFn,
  DispatchToolCallStoreFn,
  DispatchToolCallMutateFn,
  DispatchToolCallDeleteFn,
  DispatchMediaBytesStoreFn,
  DispatchRetrievableBytesStoreFn,
  ConduitBytes,
  DispatchContextHooks,
  DispatchContextHookRegistrations,
  RawDispatchRunnerInput,
  DispatchPipelineMiddlewareFn,
  DispatchExecutorFn,
  DispatchExecutorHelpers,
  DispatchExecutorLogChannel,
  DispatchExecutorLogEntry,
  DispatchExecutorLogLevel,
  LogEvent,
  WarningEvent,
  DispatchStartEvent,
  DispatchEndEvent,
  IterationStartEvent,
  IterationEndEvent,
  DispatchRunnerFunctionalHooks,
  DispatchRunnerObservabilityHooks,
  DispatchRunnerFunctionalHookRegistrations,
  DispatchRunnerObservabilityHookRegistrations,
} from './types'
